title: Materialize Jekyll
description: Materialize Theme for Jekyll, Github Pages
url: http://astro36.me/Materialize-Jekyll/
keywords: ["Programming", "Blog"]
timezone: Asia/Seoul
permalink: pretty

about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porta, odio vitae sodales malesuada, nibh diam convallis lectus, non scelerisque arcu lectus non nisi. Etiam tincidunt libero eget urna tristique faucibus. Pellentesque varius mi at placerat lobortis. Donec nec aliquam augue. Cras in gravida urna. Nulla dignissim semper accumsan. Nullam mattis felis metus, nec accumsan lorem porta et. Ut dictum dapibus est. In eu ultricies lorem. Duis semper elementum arcu, in rutrum tellus ornare eu."

author:
  codepen: 
  disqus: 
  dribbble: 
  email: astr36@naver.com
  facebook: 
  flickr: 
  foursquare: 
  github: Astro36 # required
  google_analytics: UA-77377358-3
  google_plus: 
  instagram: 
  lastfm: 
  linkedin: 
  name: Astro # required
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  telegram: psj1026
  tumblr: 
  twitter: 
  weibo: 
  xing: 
  youtube: 

paginate: 5
paginate_path: "/blog/page/:num/"

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

kramdown:
  input: GFM

sass:
  style: compressed
